services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ideasoft-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - ideasoft-network

  db:
    image: mysql:8.0
    container_name: ideasoft-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ideasoft
      MYSQL_ROOT_PASSWORD: ideasoft
      MYSQL_PASSWORD: ideasoft
      MYSQL_USER: ideasoft
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - ideasoft-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ideasoft-phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - ideasoft-network

  nginx:
    image: nginx:alpine
    container_name: ideasoft-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - ideasoft-network

networks:
  ideasoft-network:
    driver: bridge

volumes:
  dbdata:
